### ISSUE TITLE
KayTee: build failed during preparation

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/krail-testApp#27]
> com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of java.io.File out of START_OBJECT token
 at [Source: (File); line: 172, column: 23] (through reference chain: uk.q3c.kaytee.plugin.KayTeeExtension["changelog"]->uk.q3c.build.changelog.DefaultChangeLogConfiguration["outputFileSpec"])
 at [Source: (File); line: 172, column: 23] (through reference chain: uk.q3c.kaytee.plugin.KayTeeExtension["changelog"]->uk.q3c.build.changelog.DefaultChangeLogConfiguration["outputFileSpec"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at uk.q3c.kaytee.agent.prepare.DefaultLoadBuildConfiguration.execute(DefaultLoadBuildConfiguration.kt:42)
 [wrapped] uk.q3c.kaytee.agent.build.BuildPreparationException: Unable to load configuration from /home/david/kaytee-data/krail-testapp/0091cd9/krail-testapp/build/kaytee.json
	at uk.q3c.kaytee.agent.prepare.DefaultLoadBuildConfiguration.execute(DefaultLoadBuildConfiguration.kt:46)
	at uk.q3c.kaytee.agent.prepare.DefaultPreparationStage.execute(DefaultPreparationStage.kt:37)
	at uk.q3c.kaytee.agent.build.DefaultBuild.execute(DefaultBuild.kt:306)
	at uk.q3c.kaytee.agent.queue.DefaultBuildRunner.run(DefaultBuildRunner.kt:31)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davidsowerby** [comment]
Fixed by 22f8bd920fee83182302280829c93d3208934b2c
